import render from 'utils/tests/render';
import React, { Fragment, useEffect } from 'react';
import { screen } from '@testing-library/react';
import { BoundaryScreenError } from 'components/ErrorComponents';
import { ErrorBoundary } from 'react-error-boundary';

jest.mock('data/stores/useAppConfig', () => ({
  useAppConfig: () => ({
    static: {
      img: {
        marshaWhiteLogo: 'path/to/image.png',
        errorMain: 'path/to/image.png',
      },
    },
  }),
}));

const ErrorComponent = ({ withError }: { withError: boolean }) => {
  useEffect(() => {
    if (withError) {
      throw new Error('Error generated by ErrorComponent');
    }
  }, []);

  return <Fragment>No Error</Fragment>;
};

describe('<BoundaryScreenError />', () => {
  it('child component rendered without error', () => {
    render(
      <ErrorBoundary
        fallbackRender={({ error }) => (
          <BoundaryScreenError code={500} message={error.message} />
        )}
      >
        <ErrorComponent withError={false} />
      </ErrorBoundary>,
    );

    expect(screen.getByText('No Error')).toBeInTheDocument();
  });

  it('child component rendered with error', () => {
    const consoleError = jest
      .spyOn(console, 'error')
      .mockImplementation(() => jest.fn());

    render(
      <ErrorBoundary
        fallbackRender={({ error }) => (
          <BoundaryScreenError code={987} message={error.message} />
        )}
      >
        <ErrorComponent withError={true} />
      </ErrorBoundary>,
    );

    expect(screen.getByText('987')).toBeInTheDocument();
    expect(
      screen.getByText('There seems to be a slight problem:'),
    ).toBeInTheDocument();
    expect(
      screen.getByText('Error generated by ErrorComponent'),
    ).toBeInTheDocument();
    expect(consoleError).toHaveBeenCalled();
    consoleError.mockReset();
  });
});
